AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle}'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Gemfile*'
    - 'Rakefile'