version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev_password
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/picachu
      - /picachu/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium
    environment:
      POSTGRES_PASSWORD: "dev_password"
      PORT: 3000
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      TEST_APP_HOST: web
      TEST_PORT: 3001
    expose:
      - 3001
  selenium:
    # See inside via VNC with the "debug" version
#    image: selenium/standalone-chrome-debug

    # Slightly faster headless version
    image: selenium/standalone-chrome

    ports:
#      - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access
    expose:
      - 4444
#      - 5900