default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: picachu_development

test:
  <<: *default
  database: picachu_test