# From https://dev.to/heroku/deploying-to-heroku-from-github-actions-29ej
name: Push Container to Heroku

on: 
  push:
#    branches:
#      - master

env:
  HEROKU_APP_NAME: picachu-csce431

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.0
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install Bundler
        run: |
          gem install bundler
      - name: Install Gems
        run: bundle install --path vendor/bundle --jobs 20 --retry 3
      - name: Run Tests
        run: |
          bundle exec rake test
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: $HEROKU_APP_NAME
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
